version: '3.7'

services:
  web:
    restart: always
    build: ../OptchainBackend
    command: gunicorn OptchainBackend.wsgi:application -w 2 -b :8000 --reload
    volumes:
      - ../OptchainBackend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
