version: '2.2'

services:
  web:
    build:
        context: ../OptchainBackend
        dockerfile: Dockerfile.api.prod
    command: python deployment_start.py
    expose:
      - 8000
    env_file:
      - ./.env.staging
    depends_on:
      - db
      - updater
  updater:
    build:
        context: ../OptchainBackend
        dockerfile: Dockerfile.updater.prod
    command: python updatelauncher.py runserver --noreload
    env_file:
      - ./.env.staging
    cpus: '0.2'
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
