# Generated by Django 3.1.5 on 2021-01-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=25)),
                ('expiration', models.DateField()),
                ('strike', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contract_type', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], max_length=1)),
                ('latest_data', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['-strike'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(db_index=True, max_length=6)),
                ('category', models.CharField(max_length=75)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=8)),
                ('high', models.DecimalField(decimal_places=2, max_digits=8)),
                ('low', models.DecimalField(decimal_places=2, max_digits=8)),
                ('close', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume', models.PositiveIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='database.stock')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='OptionsContractPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ask', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('open_interest', models.PositiveIntegerField(blank=True, null=True)),
                ('implied_volatility', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('last_trade', models.DateTimeField()),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='database.optionscontract')),
            ],
        ),
        migrations.AddField(
            model_name='optionscontract',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='database.stock'),
        ),
    ]
